# Domo — task runner (TypeScript stack).
# Run `just` with no arguments to list everything.
#
# The broker is gone: this Mac no longer runs or dials a relay of its own. The
# outbound client that dials the Plow relay is the next piece of work, so what
# is left here is build, test, and running the app against its local state.

root    := justfile_directory()
nethome := env_var('HOME') / ".domo"

_default:
    @just --list

# ---------------------------------------------------------------------------
# Setup — build & test
# ---------------------------------------------------------------------------

# Install workspace dependencies.
install:
    npm install

# Build every package + app (tsc) and copy the desktop renderer assets.
build:
    npx tsc -b
    node apps/desktop/scripts/copy-renderer.mjs

# Run the full test suite.
test:
    npx vitest run

# Just the golden-vector conformance (fast). fixtures/ is the frozen protocol
# spec (originally generated by the now-removed Swift implementation).
test-vectors:
    npx vitest run packages/protocol packages/transport

# Package the desktop app: signed + notarized "Domo Desktop.app" + DMG, in
# apps/desktop/release/. Signs with the Plow Developer ID (must be in the
# keychain). One-time setup for notarization — store credentials under a
# keychain profile (default name "domo-notary"):
#   xcrun notarytool store-credentials domo-notary \
#       --apple-id <apple-id-email> --team-id 3559PD337Z \
#       --password <app-specific-password>
package profile="domo-notary": build
    cd "{{root}}/apps/desktop" && APPLE_KEYCHAIN_PROFILE="{{profile}}" npx electron-builder --mac

# ---------------------------------------------------------------------------
# Running the app
# ---------------------------------------------------------------------------

# Launch the desktop app against {{nethome}}.
app: build
    DOMO_HOME="{{nethome}}" npx electron "{{root}}/apps/desktop"

# Headless check that the sandboxed preload bridge and the renderer still work.
verify-preload: build
    DOMO_HOME="{{nethome}}" npx electron apps/desktop/scripts/verify-preload.mjs

# Screenshot the approval dialog (evidence that it names the calling agent).
approval-screenshot: build
    DOMO_HOME="{{nethome}}" npx electron apps/desktop/scripts/approval-screenshot.mjs

# Screenshot every first-run login screen. Fails if a screen lost its content.
onboarding-screenshots: build
    DOMO_HOME="{{nethome}}" npx electron apps/desktop/scripts/onboarding-screenshot.mjs

# Screenshot the main window's "Connect a client" screen — the OAuth route, the
# static-credential form, and the copy-once block. Uses its own throwaway home.
connect-screenshot: build
    npx electron apps/desktop/scripts/connect-screenshot.mjs

# First-run login end to end from a clean home, with the no-credential-in-a-log
# grep. Fails if any check fails.
first-run-transcript: build
    npx vite-node apps/desktop/scripts/first-run-transcript.mjs

# The chunk-10 round trip with timings: slow approval, then a long command.
slow-approval-transcript: build
    npx vite-node apps/desktop/scripts/slow-approval-transcript.mjs

# Print this Mac's device id (once the app has created its identity).
device-id:
    @node -e 'try{console.log(JSON.parse(require("fs").readFileSync("{{nethome}}/device/identity.json")).deviceId)}catch{console.log("(no device identity yet — launch the app once: just app)")}'

# Show the device's audit log (the record of everything that happened).
audit:
    @cat "{{nethome}}/device/audit.ndjson" 2>/dev/null || echo "(no audit log yet — approve something in the app first)"

# Wipe the entire app home (identity, rules, audit log, settings).
clean:
    rm -rf "{{nethome}}"
    @echo "wiped {{nethome}}"

# Drive the REAL app through the whole first run with REAL key and mouse
# events. The harness that catches a panel nobody can type in.
first-run-drive: build
    OUT_DIR="${OUT_DIR:-/tmp}" npx electron apps/desktop/scripts/first-run-drive.mjs

# The app half of the acceptance run: launch already signed in against a stack
# someone else is driving, wait for the socket, and click approvals for real.
#   PLOW_API_BASE=http://127.0.0.1:19264 PLOW_DEVICE_TOKEN=plow_… just approve-drive
approve-drive: build
    npx electron apps/desktop/scripts/approve-drive.mjs

# ---------------------------------------------------------------------------
# The relay + MCP end-to-end gate
# ---------------------------------------------------------------------------

# One command, pass/fail: OTP through the twin, device + agent credentials
# minted live, the headless device on the socket, and a real MCP call tunnelled
# to it — plus every negative. Needs a Plow variant stack up (`just up` in the
# plow worktree's api/), which is the API and the dtu-linq twin. Override the
# endpoints with RELAY_GATE_API / RELAY_GATE_TWIN.
relay-gate:
    npx vite-node e2e/relay-gate/gate.ts
