# Domo — task runner (TypeScript stack).
# Run `just` with no arguments to list everything.
#
# The broker is gone: this Mac no longer runs or dials a relay of its own. The
# outbound client that dials the Plow relay is the next piece of work, so what
# is left here is build, test, and running the app against its local state.

root    := justfile_directory()
# Empty in the main checkout; the normalized branch name in a linked git
# worktree. Worktrees get their own state (home, screenshots, Electron
# userData) keyed on this name so two checkouts can build and run side by
# side; the main checkout keeps the historical defaults. See
# scripts/worktree-setup.sh.
worktree := `sh scripts/worktree-name.sh`
nethome := if worktree == "" {
    env_var('HOME') / ".domo"
  } else {
    env_var('HOME') / ".domo-worktrees" / worktree
  }
# Where `just app` keeps state when DOMO_API_BASE_URL points somewhere other
# than production. A credential is only valid against the environment that
# minted it, so `export DOMO_API_BASE_URL=…; just app` must never write a local
# credential into the production install's settings file. An explicit DOMO_HOME
# still wins.
localhome := if worktree == "" {
    env_var('HOME') / ".domo-local"
  } else {
    env_var('HOME') / ".domo-worktrees" / (worktree + "-local")
  }
apphome   := if env_var_or_default("DOMO_HOME", "") != "" {
    env_var_or_default("DOMO_HOME", "")
  } else if env_var_or_default("DOMO_API_BASE_URL", "") != "" {
    localhome
  } else {
    nethome
  }
# Where the evidence scripts drop screenshots. Per-worktree so simultaneous
# runs don't clobber each other's output; explicit OUT/OUT_DIR/SETTINGS_OUT
# env vars still win inside the recipes.
outdir := if worktree == "" { "/tmp" } else { "/tmp/domo-" + worktree }

_default:
    @just --list

# ---------------------------------------------------------------------------
# Setup — build & test
# ---------------------------------------------------------------------------

# Install workspace dependencies.
install:
    npm install

# Build every package + app (tsc) and copy the desktop renderer assets.
build:
    npx tsc -b
    node apps/desktop/scripts/copy-renderer.mjs

# Run the full test suite.
test:
    npx vitest run

# Just the golden-vector conformance (fast). fixtures/ is the frozen protocol
# spec (originally generated by the now-removed Swift implementation).
test-vectors:
    npx vitest run packages/protocol packages/transport

# ---------------------------------------------------------------------------
# Browser runtime (Camoufox + bundled Python) — see vendor/browser-server/
# ---------------------------------------------------------------------------

# Build the universal Python 3.12 runtime for the browser stack into
# vendor/python-runtime (cached by pin stamp; ~5 min + ~200 MB downloads cold).
fetch-browser-runtime:
    node scripts/build-browser-runtime.mjs

# Fetch the Camoufox browser for THIS Mac's arch into vendor/camoufox-browser
# (dev + integration tests; ~320 MB).
fetch-browser:
    node scripts/build-browser-runtime.mjs --browser

# Both arches (what `just package` bundles into the DMG; ~640 MB).
fetch-browser-both:
    node scripts/build-browser-runtime.mjs --browser-both

# Run the real-browser integration tier: real Python runtime + real Camoufox
# ordering a pizza on a local fixture site through the MCP server on the Mac.
# Needs `just fetch-browser-runtime fetch-browser` first.
test-browser: build
    DOMO_BROWSER_RUNTIME="{{root}}/vendor" \
    DOMO_CAMOUFOX="{{root}}/vendor/camoufox-browser/$(uname -m)" \
        npx vitest run packages/mcp-server/test/browser.integration.test.ts

# Package the desktop app: signed + notarized "Domo Desktop.app" + DMG, in
# apps/desktop/release/. Signs with the Plow Developer ID (must be in the
# keychain). One-time setup for notarization — store credentials under a
# keychain profile (default name "domo-notary"):
#   xcrun notarytool store-credentials domo-notary \
#       --apple-id <apple-id-email> --team-id 3559PD337Z \
#       --password <app-specific-password>
# The browser stack ships inside the DMG: the universal Python runtime and
# BOTH Camoufox arches are built/fetched, then Developer-ID signed by the
# afterPack hook AFTER electron-builder's universal merge (which rewrites nested
# Info.plists and would break any earlier signature). CODESIGN_IDENTITY is
# passed to electron-builder so the hook can sign; the build step itself leaves
# the payload unsigned (afterPack is authoritative).
# Packaging runs from the main checkout only: worktrees share the per-user
# electron-builder caches and the signing/notary keychain state, so concurrent
# packages would race, and the DMG should come from main anyway.
_main-only:
    @if [ -n "{{worktree}}" ]; then echo "error: just package runs from the main checkout only (this is worktree '{{worktree}}')" >&2; exit 1; fi

package profile="domo-notary": _main-only build
    node scripts/build-browser-runtime.mjs --browser-both
    cd "{{root}}/apps/desktop" && CODESIGN_IDENTITY="The Plow Collective, Inc (3559PD337Z)" APPLE_KEYCHAIN_PROFILE="{{profile}}" npx electron-builder --mac

# ---------------------------------------------------------------------------
# Running the app
# ---------------------------------------------------------------------------

# Every build talks to production. To point somewhere else, export the override
# yourself — and the home moves with it so a local credential never overwrites
# the production install's:
#
#   just app                                            # production, {{nethome}}
#   DOMO_API_BASE_URL=http://localhost:4242 just app    # that relay, {{localhome}}
#   DOMO_HOME=~/.domo-x just app                        # an explicit home wins
#
# In a linked git worktree both defaults move under ~/.domo-worktrees/<branch>
# so worktrees run side by side with main. Each home signs in on its own —
# never copy a relay credential between homes (the relay does not support two
# devices on one credential).

# Launch the desktop app. DOMO_WORKTREE brands a worktree's instance (app
# name, tray tooltip, Electron userData dir) so it never collides with the
# main checkout's; it is empty — and changes nothing — on main.
app: build
    DOMO_HOME="{{apphome}}" DOMO_WORKTREE="{{worktree}}" npx electron "{{root}}/apps/desktop"

# Headless check that the sandboxed preload bridge and the renderer still work.
verify-preload: build
    @mkdir -p "{{outdir}}"
    DOMO_HOME="{{apphome}}" SETTINGS_OUT="${SETTINGS_OUT:-{{outdir}}/settings-account.png}" npx electron apps/desktop/scripts/verify-preload.mjs

# Screenshot the approval dialog (evidence that it names the calling agent).
approval-screenshot: build
    @mkdir -p "{{outdir}}"
    DOMO_HOME="{{apphome}}" OUT="${OUT:-{{outdir}}/approval-dialog.png}" npx electron apps/desktop/scripts/approval-screenshot.mjs

# Screenshot every first-run login screen. Fails if a screen lost its content.
onboarding-screenshots: build
    @mkdir -p "{{outdir}}"
    DOMO_HOME="{{apphome}}" OUT_DIR="${OUT_DIR:-{{outdir}}}" npx electron apps/desktop/scripts/onboarding-screenshot.mjs

# First-run login end to end from a clean home, with the no-credential-in-a-log
# grep. Fails if any check fails.
first-run-transcript: build
    npx vite-node apps/desktop/scripts/first-run-transcript.mjs

# The chunk-10 round trip with timings: slow approval, then a long command.
slow-approval-transcript: build
    npx vite-node apps/desktop/scripts/slow-approval-transcript.mjs

# Print this Mac's device id (once the app has created its identity).
device-id:
    @node -e 'try{console.log(JSON.parse(require("fs").readFileSync("{{apphome}}/device/identity.json")).deviceId)}catch{console.log("(no device identity yet — launch the app once: just app)")}'

# Show the device's audit log (the record of everything that happened).
audit:
    @cat "{{apphome}}/device/audit.ndjson" 2>/dev/null || echo "(no audit log yet — approve something in the app first)"

# Wipe THIS checkout's app home (identity, rules, audit log, settings) — on a
# worktree that is the worktree's home, never the main checkout's.
clean:
    rm -rf "{{apphome}}"
    @echo "wiped {{apphome}}"

# Drive the REAL app through the whole first run with REAL key and mouse
# events. The harness that catches a panel nobody can type in.
first-run-drive: build
    @mkdir -p "{{outdir}}"
    OUT_DIR="${OUT_DIR:-{{outdir}}}" npx electron apps/desktop/scripts/first-run-drive.mjs

# The app half of the acceptance run: launch already signed in against a stack
# someone else is driving, wait for the socket, and click approvals for real.
#   PLOW_API_BASE=http://127.0.0.1:19264 PLOW_DEVICE_TOKEN=plow_… just approve-drive
approve-drive: build
    npx electron apps/desktop/scripts/approve-drive.mjs

# ---------------------------------------------------------------------------
# The relay + MCP end-to-end gate
# ---------------------------------------------------------------------------

# One command, pass/fail: OTP through the twin, device + agent credentials
# minted live, the headless device on the socket, and a real MCP call tunnelled
# to it — plus every negative. Needs a Plow variant stack up (`just up` in the
# plow worktree's api/), which is the API and the dtu-linq twin. Override the
# endpoints with RELAY_GATE_API / RELAY_GATE_TWIN.
relay-gate:
    npx vite-node e2e/relay-gate/gate.ts
