/**
 * Golden-vector conformance: every fixture in fixtures/ is the frozen protocol
 * spec (originally generated by the now-removed Swift implementation). These
 * tests prove the code produces byte-identical canonical JSON, signatures, rule
 * keys, connection strings, and path canonicalization.
 */
import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  Capability,
  DeviceChallenge,
  DomoConnection,
  Hashing,
  Intent,
  KeyPair,
  RuleKey,
  canonicalJSON,
  canonicalize,
  compactString,
  deepLink,
  grantSigningData,
  intentRuleKey,
  intentSigningData,
  parseConnection,
  signGrant,
  signIntent,
  verifyIntentSignature,
} from "@domo/protocol";
import type { Grant, JSONValue } from "@domo/protocol";

const fixturesDir = fileURLToPath(new URL("../../../fixtures", import.meta.url));

function fixture<T = any>(name: string): T {
  return JSON.parse(fs.readFileSync(path.join(fixturesDir, name), "utf8")) as T;
}

describe("canonical JSON", () => {
  const { cases } = fixture("canonical-json.json");
  for (const c of cases) {
    it(c.name, () => {
      expect(canonicalJSON(c.value as JSONValue)).toBe(c.canonical);
    });
  }
});

describe("identity", () => {
  const f = fixture("identity.json");
  const keys = new Map<string, KeyPair>(
    f.keys.map((k: any) => [k.name, KeyPair.fromRawRepresentation(Buffer.from(k.seedBase64, "base64"))]),
  );

  it("public keys and fingerprints", () => {
    for (const k of f.keys) {
      const kp = keys.get(k.name)!;
      expect(kp.publicKeyBase64).toBe(k.publicKeyBase64);
      expect(kp.fingerprint).toBe(k.fingerprint);
    }
  });

  // NOTE: CryptoKit's Ed25519 signatures are RANDOMIZED (Apple adds entropy
  // for side-channel resistance), so Swift signature bytes differ run-to-run.
  // Conformance is therefore cross-VERIFICATION: Swift-made signatures must
  // verify here, and TS-made signatures verify under the same public keys.
  it("signatures cross-verify", () => {
    const message = Buffer.from(f.message, "utf8");
    expect(
      KeyPair.verify(Buffer.from(f.signatureA, "base64"), message, keys.get("A")!.publicKeyBase64),
    ).toBe(true);
    expect(
      KeyPair.verify(Buffer.from(f.signatureB, "base64"), message, keys.get("B")!.publicKeyBase64),
    ).toBe(true);
    const tsSig = keys.get("A")!.sign(message);
    expect(KeyPair.verify(tsSig, message, keys.get("A")!.publicKeyBase64)).toBe(true);
    expect(
      KeyPair.verify(Buffer.from(f.signatureA, "base64"), message, keys.get("B")!.publicKeyBase64),
    ).toBe(false);
    expect(Hashing.sha256Hex(message)).toBe(f.sha256HexOfMessage);
  });
});

describe("intent / grant / rule", () => {
  const f = fixture("intent.json");
  const identity = fixture("identity.json");
  const keyA = KeyPair.fromRawRepresentation(Buffer.from(identity.keys[0].seedBase64, "base64"));
  const keyB = KeyPair.fromRawRepresentation(Buffer.from(identity.keys[1].seedBase64, "base64"));

  it("signing bytes match Swift byte-for-byte", () => {
    const intent = { ...f.intent } as Intent;
    delete intent.signature;
    expect(intentSigningData(intent).toString("utf8")).toBe(f.signingData);
  });

  it("Swift's intent signature verifies here; TS signature verifies too", () => {
    // Swift-signed intent (from the fixture) verifies in TS…
    expect(verifyIntentSignature(f.intent as Intent)).toBe(true);
    // …and a TS-signed copy verifies under the same key.
    const intent = { ...f.intent } as Intent;
    delete intent.signature;
    signIntent(intent, keyA);
    expect(verifyIntentSignature(intent)).toBe(true);
    // Tampering breaks it.
    const tampered = { ...f.intent, request: "run: rm -rf /" } as Intent;
    expect(verifyIntentSignature(tampered)).toBe(false);
  });

  it("rule key matches", () => {
    expect(intentRuleKey(f.intent as Intent)).toBe(f.ruleKey);
  });

  it("grant signing bytes match; signatures cross-verify", () => {
    const grant = { ...f.grant } as Grant;
    delete grant.deviceSignature;
    expect(grantSigningData(grant).toString("utf8")).toBe(f.grantSigningData);
    expect(
      KeyPair.verify(
        Buffer.from(f.grantSignature, "base64"),
        grantSigningData(grant),
        keyB.publicKeyBase64,
      ),
    ).toBe(true);
    signGrant(grant, keyB);
    expect(
      KeyPair.verify(
        Buffer.from(grant.deviceSignature!, "base64"),
        grantSigningData(grant),
        keyB.publicKeyBase64,
      ),
    ).toBe(true);
  });
});

describe("rule keys", () => {
  const { cases } = fixture("rulekeys.json");
  for (const c of cases) {
    it(c.name, () => {
      expect(RuleKey.compute(c.agentId, c.deviceId, c.capabilitiesA as Capability[])).toBe(c.ruleKey);
      if (c.capabilitiesB) {
        expect(RuleKey.compute(c.agentId, c.deviceId, c.capabilitiesB as Capability[])).toBe(c.ruleKey);
      }
    });
  }
});

describe("connection strings", () => {
  const { cases } = fixture("connection.json");
  for (const c of cases) {
    it(c.url, () => {
      const conn: DomoConnection = {
        url: c.url,
        pin: c.pin ?? undefined,
        token: c.token ?? undefined,
        name: c.name ?? undefined,
        authenticate: c.authenticate,
      };
      expect(compactString(conn)).toBe(c.compact);
      expect(deepLink(conn)).toBe(c.deepLink);
      // Parse round-trips (all three accepted forms).
      expect(parseConnection(c.compact)).toEqual(conn);
      expect(parseConnection(c.deepLink)).toEqual(conn);
    });
  }
  it("bare URL parse", () => {
    expect(parseConnection("ws://127.0.0.1:1234/")).toEqual({
      url: "ws://127.0.0.1:1234/",
      pin: undefined,
      token: undefined,
      name: undefined,
      authenticate: false,
    });
  });
});

describe("device challenge", () => {
  const f = fixture("challenge.json");
  const identity = fixture("identity.json");
  const keyA = KeyPair.fromRawRepresentation(Buffer.from(identity.keys[0].seedBase64, "base64"));

  it("matches Swift context, bytes, and signature", () => {
    expect(DeviceChallenge.context).toBe(f.context);
    expect(DeviceChallenge.signingData(f.nonce).toString("base64")).toBe(f.signingDataBase64);
    // Swift's (randomized) signature verifies here; ours verifies too.
    expect(DeviceChallenge.verify(f.nonce, f.signatureA, keyA.publicKeyBase64)).toBe(true);
    expect(
      DeviceChallenge.verify(f.nonce, DeviceChallenge.sign(f.nonce, keyA), keyA.publicKeyBase64),
    ).toBe(true);
    expect(DeviceChallenge.verify("other-nonce", f.signatureA, keyA.publicKeyBase64)).toBe(false);
  });
});

describe("path canonicalization", () => {
  const f = fixture("pathutil.json");
  for (const c of f.cases) {
    it(c.input, () => {
      if (!c.input.startsWith("/") && process.cwd() !== f.cwdAtGeneration) {
        // Relative-path case is only meaningful from the generator's cwd.
        return;
      }
      expect(canonicalize(c.input)).toBe(c.canonical);
    });
  }
});
