/**
 * Golden-vector conformance: every fixture in fixtures/ is the frozen protocol
 * spec (originally generated by the now-removed Swift implementation). These
 * tests prove the code produces byte-identical canonical JSON, device
 * signatures, rule keys, and path canonicalization.
 */
import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  Capability,
  Hashing,
  Intent,
  KeyPair,
  RuleKey,
  canonicalJSON,
  canonicalize,
  grantSigningData,
  intentRuleKey,
  signGrant,
} from "@domo/protocol";
import type { Grant, JSONValue } from "@domo/protocol";

const fixturesDir = fileURLToPath(new URL("../../../fixtures", import.meta.url));

function fixture<T = any>(name: string): T {
  return JSON.parse(fs.readFileSync(path.join(fixturesDir, name), "utf8")) as T;
}

describe("canonical JSON", () => {
  const { cases } = fixture("canonical-json.json");
  for (const c of cases) {
    it(c.name, () => {
      expect(canonicalJSON(c.value as JSONValue)).toBe(c.canonical);
    });
  }
});

describe("identity", () => {
  const f = fixture("identity.json");
  const keys = new Map<string, KeyPair>(
    f.keys.map((k: any) => [k.name, KeyPair.fromRawRepresentation(Buffer.from(k.seedBase64, "base64"))]),
  );

  it("public keys and fingerprints", () => {
    for (const k of f.keys) {
      const kp = keys.get(k.name)!;
      expect(kp.publicKeyBase64).toBe(k.publicKeyBase64);
      expect(kp.fingerprint).toBe(k.fingerprint);
    }
  });

  // NOTE: CryptoKit's Ed25519 signatures are RANDOMIZED (Apple adds entropy
  // for side-channel resistance), so Swift signature bytes differ run-to-run.
  // Conformance is therefore cross-VERIFICATION: Swift-made signatures must
  // verify here, and TS-made signatures verify under the same public keys.
  it("signatures cross-verify", () => {
    const message = Buffer.from(f.message, "utf8");
    expect(
      KeyPair.verify(Buffer.from(f.signatureA, "base64"), message, keys.get("A")!.publicKeyBase64),
    ).toBe(true);
    expect(
      KeyPair.verify(Buffer.from(f.signatureB, "base64"), message, keys.get("B")!.publicKeyBase64),
    ).toBe(true);
    const tsSig = keys.get("A")!.sign(message);
    expect(KeyPair.verify(tsSig, message, keys.get("A")!.publicKeyBase64)).toBe(true);
    expect(
      KeyPair.verify(Buffer.from(f.signatureA, "base64"), message, keys.get("B")!.publicKeyBase64),
    ).toBe(false);
    expect(Hashing.sha256Hex(message)).toBe(f.sha256HexOfMessage);
  });
});

describe("intent / grant / rule", () => {
  const f = fixture("intent.json");
  const identity = fixture("identity.json");
  const keyB = KeyPair.fromRawRepresentation(Buffer.from(identity.keys[1].seedBase64, "base64"));

  it("the frozen intent carries no agent key and no agent signature", () => {
    // D1: an Intent is built on this Mac from an authenticated agent's call, so
    // there is nothing for the agent to sign and no key to carry.
    expect(f.intent).not.toHaveProperty("agentPublicKey");
    expect(f.intent).not.toHaveProperty("signature");
  });

  it("rule key matches", () => {
    expect(intentRuleKey(f.intent as Intent)).toBe(f.ruleKey);
  });

  it("grant signing bytes match; signatures cross-verify", () => {
    const grant = { ...f.grant } as Grant;
    delete grant.deviceSignature;
    expect(grantSigningData(grant).toString("utf8")).toBe(f.grantSigningData);
    expect(
      KeyPair.verify(
        Buffer.from(f.grantSignature, "base64"),
        grantSigningData(grant),
        keyB.publicKeyBase64,
      ),
    ).toBe(true);
    signGrant(grant, keyB);
    expect(
      KeyPair.verify(
        Buffer.from(grant.deviceSignature!, "base64"),
        grantSigningData(grant),
        keyB.publicKeyBase64,
      ),
    ).toBe(true);
  });
});

describe("rule keys", () => {
  const { cases } = fixture("rulekeys.json");
  for (const c of cases) {
    it(c.name, () => {
      expect(RuleKey.compute(c.agentId, c.deviceId, c.capabilitiesA as Capability[])).toBe(c.ruleKey);
      if (c.capabilitiesB) {
        expect(RuleKey.compute(c.agentId, c.deviceId, c.capabilitiesB as Capability[])).toBe(c.ruleKey);
      }
    });
  }
});

describe("path canonicalization", () => {
  const f = fixture("pathutil.json");
  for (const c of f.cases) {
    it(c.input, () => {
      if (!c.input.startsWith("/") && process.cwd() !== f.cwdAtGeneration) {
        // Relative-path case is only meaningful from the generator's cwd.
        return;
      }
      if (process.platform !== "darwin" && c.canonical.startsWith("/private/")) {
        // These cases encode macOS's /tmp|/var|/etc → /private symlinks.
        return;
      }
      expect(canonicalize(c.input)).toBe(c.canonical);
    });
  }
});
